Patch for SQL Alchemy deserializer error
Attempting to use PinotDB with SQL Alchemy produced the following error related to a missing method:

Traceback (most recent call last):
        File "...sqlalchemy/sql/sqltypes.py", line 2714, in result_processor
        json_deserializer = dialect._json_deserializer or json.loads
        AttributeError: 'PinotDialect' object has no attribute '_json_deserializer'

This provides that method and avoids the error.